
-- AMAZON AWS
CREATE BIGFILE TABLESPACE "DATOS" DATAFILE '/u02/oradata/clouddp/datos.dat'
SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT 
SPACE MANAGEMENT AUTO DEFAULT NOCOMPRESS;

create or replace directory "IMAGENES" as '/var/Carga_Oracle';

-- RackSpace

-- local
CREATE BIGFILE TABLESPACE "DATOS" DATAFILE 'E:\app\Administrador\oradata\clouddp\datos.dat' 
SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT 
SPACE MANAGEMENT AUTO DEFAULT NOCOMPRESS;

create or replace directory "IMAGENES" as 'C:\Carga_Oracle';

--
-- ASIGNAR PERMISOS A EL USUARIO
--

-- usuario system

CREATE USER "CLOUD_DP_BETA12" PROFILE "DEFAULT" IDENTIFIED BY "a1" DEFAULT TABLESPACE "DATOS" 
TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

GRANT "CONNECT" TO "CLOUD_DP_BETA12";

-- solo usuario sys

GRANT EXECUTE ON "SYS"."DBMS_CRYPTO" TO "CLOUD_DP_BETA12";


-- solo para programación no es posible usarloen explotación
GRANT "DBA" TO "CLOUD_DP_BETA12" WITH ADMIN OPTION;


-- solo para programación no es posible usarlo en explotación
GRANT EXECUTE ON "SYS"."DBMS_OUTPUT" TO "CLOUD_DP_BETA1"




-- CREAR UN INDICE
CREATE INDEX CLIENTE_DOC ON DOC_CUSTODIA (CLIENTE);	

-- TABLAS

SELECT 'DROP sequence CLOUD_DP_BETA1.'||OBJECT_NAME||';'  FROM  ALL_OBJECTS WHERE OWNER='CLOUD_DP_BETA1' 
AND OBJECT_TYPE='SEQUENCE' AND TIMESTAMP>'2001-05-08:08:00:00';

-- SECUENCIAS
SELECT 'DROP sequence CLOUD_DP_BETA1.'||OBJECT_NAME||';'  FROM  ALL_OBJECTS WHERE OWNER='CLOUD_DP_BETA1' 
AND OBJECT_TYPE='SEQUENCE' AND TIMESTAMP>'2001-05-08:08:00:00';

-- DISPARADORES
SELECT 'DROP TRIGGER CLOUD_DP_BETA1.'||OBJECT_NAME||';'  FROM  ALL_OBJECTS WHERE OWNER='CLOUD_DP_BETA1' 
AND OBJECT_TYPE='TRIGGER' AND TIMESTAMP>'2001-05-08:08:00:00';

-- PROCEDIMIENTOS
SELECT 'DROP PROCEDURE CLOUD_DP_BETA1.'||OBJECT_NAME||';'  FROM  ALL_OBJECTS WHERE OWNER='CLOUD_DP_BETA1' 
AND OBJECT_TYPE='PROCEDURE' AND TIMESTAMP>'2001-05-08:08:00:00';

