

REM Insertar la clave privada del servicio de firma del sistema
rem CONFIGURACIÓN A REALIZAR TRAS LA INSTALACIÓN
REM INSERTING into REDMOON
Insert into REDMOON (ID,RAZON_SOCIAL,CIF,DIRECCION,FACTURA,YEAR,IVA) 
	values (1,'Servicio Beta12','B18874941','Magdalena 7',1,'2010',18);

-- http://www.redmoon.es/admin/CloudDP/SubirPrivada.php


REM INSERTING into SERVICIOS


REM Servicios de precio reducido.

REM sin coste para el suscriptor (Free)
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (1,'FREE',0,'PAGO POR USO','MES',18);

REM  Documento que va a estar cifrado en la nube
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (2,'AES256',0.05,'PAGO POR USO','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (3,'FIRMA',0.35,'PAGO POR USO','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (4,'SELLADO DE TIEMPO EDICOM',0.4,'PAGO POR USO','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (5,'CUSTODIA Y FIRMA NOTARIAL',0.75,'PAGO POR USO','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (6,'ESCANEADO DOCUMENTOS',0.05,'PAGO POR USO','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (7,'ENVIO SMS',0.14,'PAGO POR USO','MES',18);

REM se trata de generar una URL de una sola lectura utilizada para los servicios de pago por visión.
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (8,'OneTimeURL',0.05,'PAGO POR USO','MES',18);

-- pagos domiciliados
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (9,'SUSCRIPCION CDP',70,'SUSCRIPCION','MES',18);
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (10,'CONSULTORIA MES DE',480,'SERVICIOS','MES',18);
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (11,'DOMINIO Y SERVIDOR DE CORREO',25,'HOSTING','MES',18);
Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (12,'OFERTA ORDENADOR+CLOUD_DP',50,'SUSCRIPCION','MES',18);

Insert into SERVICIOS (ID,SERVICIO,PRECIO,MODALIDAD,PERIODICIDAD,TIPO_IVA) values (13,'WF_FACTURAS',0.20,'PAGO POR USO','MES',18);

REM INSERTING into GREMIOS
Insert into GREMIOS (ID,NOMBRE,BUCKET) values (1,'ASESORIA FISCAL Y CONTABLE Asesorias','asesorias');

REM INSERTING into GREMIOS_CORPUS
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'FACTURA EMITIDA');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'NUMERO FACTURA');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'FECHA FACTURA');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'AÑO');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'TRIMESTRE');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'RESUMEN ANUAL');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'BALANCE SITUACION');
Insert into GREMIOS_CORPUS (ID_GREMIO,ATRIBUTO) values (1,'BALANCE DE PERDIDAS Y GANACIAS');


-- USOS DE CERTIFICADO EL METODO DE CIFRADO POR DEFECTO
INSERT INTO USOS_CERTIFICADO (ID, DESCRIPCION) VALUES (1, 'CIFRAR AES');

--valores de VISTASINTERFAZ
INSERT INTO VISTASINTERFAZ  (NOMBRE_INTERFAZ,ETIQUETA,EXPLICACION,IDIOMA,SERVICIO,OBJETO,CARPETA) 
VALUES('Subir File Asesor','Cifrar Documento',
	'Convertimos mediante la criptografia la información legible en información que no se puede leer directamente, sino que ha de ser descifrada para ser leída. Aplicada a mensajes digitales, proporciona las herramientas idóneas para solucionar los problemas de confidencialidad y autenticidad.',
	'ES','AES256','ListServicios','ListServicios');
	
INSERT INTO VISTASINTERFAZ  (NOMBRE_INTERFAZ,ETIQUETA,EXPLICACION,IDIOMA,SERVICIO,OBJETO,CARPETA) 
VALUES('Subir File Asesor','Firmar Documento',
	'Firmado en el sistema por una firma digital avanzada basada en tercero de confianza con plena validez legal, se garantizan todos los supuestos de integridad, no repudio, etc.',
	'ES','FIRMA','ListServicios','ListServicios');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,EXPLICACION,IDIOMA,SERVICIO,OBJETO,CARPETA)
 VALUES('Subir File Asesor','Firma y Sello de Tiempo',
	'¿Para qué utilizar el sellado de tiempo? Cuando se realizan operaciones en Internet el conocimiento del tiempo es importante y solicitar a un tercero de confianza que de constancia de la fecha y hora es fundamental a la hora de aportar pruebas, garantizar la fuente de tiempo empleada y asegurar la integridad de los datos así sellados. El sellado de tiempo es un método para probar que un conjunto de datos existió antes de un momento dado y que ninguno de estos datos ha sido modificado desde entonces. ',
	'ES','SELLADO DE TIEMPO','ListServicios','ListServicios');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','Nominas',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','Facturas Emitidas',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','Facturas Recibidas',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','Balances y pagos de Tributos',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','Alquileres',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','IVA Intracomunitario Emitido',
	'ES','FREE','treeTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Subir File Asesor','IVA Intracomunitario Recibido',
	'ES','FREE','treeTipoArchivo','docs');
	
--
--Lista de tipos de documentos que pude tener un asesor
--
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Nominas',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Facturas Emitidas',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Facturas Recibidas',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Balances y pagos de Tributos',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Alquileres',
	'ES','FREE','gridTipoArchivo','docs');
	
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','IVA Intracomunitario Emitido',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','IVA Intracomunitario Recibido',
	'ES','FREE','gridTipoArchivo','docs');
	
INSERT INTO VISTASINTERFAZ (NOMBRE_INTERFAZ,ETIQUETA,IDIOMA,SERVICIO,OBJETO,CARPETA)
	VALUES('Docs Asesor','Mis Documentos','ES','FREE','gridTipoArchivo','misDocs');
	

	
	




--
--
INSERT INTO CONSULTAS(NOMBRE,IDGREMIO) VALUES ('operacion credito',1);
INSERT INTO CONSULTAS(NOMBRE,IDGREMIO) VALUES ('libros de iva',1);

--operacion credito
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='operacion credito'),'303');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='operacion credito'),'IMPUESTO DE SOCIEDADES');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='operacion credito'),'BALANCE DE SITUACION');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='operacion credito'),'110');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='operacion credito'),'CUENTA DE PERDIDAS Y GANANCIAS');

--libro de iva
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='libros de iva'),'Facturas Emitidas');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='libros de iva'),'Facturas Recibidas');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='libros de iva'),'IVA Intracomunitario Emitido');
INSERT INTO DOCCONSULTA(ID_CONSULTA,TIPO_DOC) 
VALUES ((SELECT ID FROM CONSULTAS WHERE NOMBRE='libros de iva'),'IVA Intracomunitario Recibido');


--

 INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('110',1,'IRPF','TR','110'); 
 	
 INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('115',1,'RETENCIONES DE ALQUILER','TR','115');
 	
 
 	
  INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('216',1,'RETENCIONES DE ALQUILER - NO RESIDENTES','TR','216');
 		
  INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('349',1,'IVA INTRACOMUNITARIO','TR','349');
 	
 	
  INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('390',1,'RESUMEN ANUAL DE IVA','AN','390');
 	 	
 	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('180',1,'RESUMEN ANUAL DE ALQUILERES','AN','180');
 	
  	
 	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('296',1,'RESUMEN ANUAL DE ALQUILERES - NO RESIDENTES','AN','296');
 	
 	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('190',1,'RESUMEN ANUAL DE IRPF','AN','190');
 		
 	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('347',1,'RESUMEN ANUAL DE FACTURACIONA CLIENTES DE MAS DE 3000€','AN','347');
 	
	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('201',1,'RESUMEN ANUAL DEL IMPUESTO DE SOCIEDADES','AN','201');
 	
 	
   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('202',1,'PAGOS FRACCIONADOS A CUENTA DEL IMPUESTO DE SOCIEDADES','ME','202');
 	
 	
  INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('Balance de situacion',1,'BALANCE DE SITUACION','ME','BALANCE DE SITUACION');
 	
  INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('Cuenta de Perdidas y Ganacias',1,'CUENTA DE PERDIDAS Y GANACIAS','ME','CUENTA DE PERDIDAS Y GANACIAS');
 	
 	   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('303',1,'IMPUESTO SOBRE VALOR AÑADIDO','TR','303');
 	
 		   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('036',1,'DECLARACION CENSAL','AN','036');
 	
 		   INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('Operaciones con terceros Anual',1,'RESUMEN OPERACIONES CON TERCEROS','AN','036');
 	
 INSERT INTO TIPOS_DOC (ETIQUETA,IDGREMIO,DESCRIPCION,PERIODO,TIPO_DOCUMENTO)
 	VALUES ('200',1,'IMPUESTO DE SOCIEDADES','AN','200');
--
--
INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='110'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='115'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='216'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='349'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='390'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='180'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='296'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='190'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='347'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='201'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='202'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='036'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='303'));

--INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='emitidas'));

--INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='recibidas'));

--INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='ivaintra_recibidas'));

--INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='ivaintra_emitidas'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='BALANCE DE SITUACION'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='CUENTA DE PERDIDAS Y GANACIAS'));

INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='RESUMEN OPERACIONES CON TERCEROS'));


INSERT INTO FORMASJURIDICAS (FORMA,IDTIPO_DOC) VALUES ('SL',(SELECT ID FROM TIPOS_DOC WHERE TIPO_DOCUMENTO='200'));





