-- CLIENTE TIPO LGS
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (8,480,41);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (9,25,41);

--CLIENTE TIPO ASESORIA FISCAL
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (1,70,1);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (3,0.35,1);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (3,0.35,1);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (3,0.35,1);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (4,0.75,1);
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (4,0.75,1);

--OFERTA ORDENADOR
INSERT INTO CONSUMOS (ID_SERVICIO,PRECIO,IDCLIENTE) VALUES (10,50,22);