--USUARIO CLOUDDP
--crear el usuario clouddp 
------------------------------------COMO SYS------------------------------------------------
CREATE USER "CLOUD_DP_BETA15" PROFILE "DEFAULT" IDENTIFIED BY "a1" DEFAULT TABLESPACE "DATOS" 
TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

GRANT "CONNECT" TO "CLOUD_DP_BETA15";

-- solo usuario sys

GRANT EXECUTE ON "SYS"."DBMS_CRYPTO" TO "CLOUD_DP_BETA15";


-- solo para programación no es posible usarloen explotación
GRANT "DBA" TO "CLOUD_DP_BETA15" WITH ADMIN OPTION;


--------------------CREAR TODOS LOS OBJETOS DE LA BASE DE DATOS-----------------------------------------
---------------------------------------------------------------------------------------------------------


------------------------------------COMO CLOUDDP BETA 15------------------------------------------------

--LOGIN
-- Este usuario solo está autorizado a ejecutar el programa pkLogin.
CREATE ROLE "LOGIN_X509" NOT IDENTIFIED;
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKLOGIN" TO "LOGIN_X509";
GRANT "CONNECT" TO "LOGIN_X509";


CREATE USER "LOGIN" PROFILE "DEFAULT" IDENTIFIED BY "A1" DEFAULT TABLESPACE "DATOS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "CONNECT" TO "LOGIN";
GRANT "LOGIN_X509" TO "LOGIN";

--CREAR el sinonimo publico para el paquete login.
-- 
CREATE PUBLIC SYNONYM PKLOGIN FOR CLOUD_DP_BETA15.PKLOGIN;

--CREAMOS EL USUSARIO CL
CREATE USER CL IDENTIFIED BY a1;

--CREAMOS EL ROL CLIENTE_CLOUDDP
CREATE ROLE "CLIENTE_CLOUDDP" NOT IDENTIFIED;



---------------------------------DESPUES DE CREAR TODOS LOS OBJETOS DEL USUARIO CDP BETAB 15---------------
--PROCEDIEMIENTOS Y FUNCIONES

GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETALMACENCERT" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETCLIENTDTOANDGROUP" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETCONNUSER" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETDEFAULTDTOANDGROUP" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETSESION" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PGETMIMETYPEBYIDDOC" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."NOMBRESERVICIOFINDBYID" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."FORMAJURIDICABYNIF" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETBUCKET" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GETURLNUBE" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."GET_DOCCONSULTA" TO "CLIENTE_CLOUDDP";



--PAQUETES
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKCONSULTASFISCAL" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKCRIPTOCLOUDDP" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKDOCSYSTEMCUSTODY" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKEDITUSUARIOS" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKMENSAJES" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKSESIONES" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKUSERSCDP" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKWORKFORCE" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKTABLON" TO "CLIENTE_CLOUDDP";
GRANT EXECUTE ON "CLOUD_DP_BETA15"."PKCARPETAS" TO "CLIENTE_CLOUDDP";


--VISTAS
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_DOCSINVITADO" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_DOCSCLIENTE" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_EMPLEADOS" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_INVITADOS" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_INVITADOSACTIVOS" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_INVITADOSBAJA" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_BUZONENTRADA" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_BUZONSALIDA" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_ASUNTOSPENDIENTES" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."VW_HILOS" TO "CLIENTE_CLOUDDP";

--TABLAS
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."WEB_PERSONAL" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TIPOS_DOC" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TEMPCONSULTAS" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."VISTASINTERFAZ" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TABLON" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."FORMASJURIDICAS" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TMP_CORPUS" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TMPBLOB" TO "CLIENTE_CLOUDDP";
GRANT SELECT,INSERT,UPDATE,DELETE ON "CLOUD_DP_BETA15"."TEMP_CARPETAS" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."CONSULTAS" TO "CLIENTE_CLOUDDP";
GRANT SELECT ON "CLOUD_DP_BETA15"."CARPETASUSUARIO" TO "CLIENTE_CLOUDDP";


--ASOCIAMOS EL USUSARIO CL A EL ROL CLIENTE_CLOUDDP
GRANT "CONNECT" TO "CL";
GRANT "CLIENTE_CLOUDDP" TO "CL";

--



CREATE PUBLIC SYNONYM ACCESSMS FOR "CLOUD_DP_BETA15"."ACCESSMS" ;
CREATE PUBLIC SYNONYM GETALMACENCERT FOR "CLOUD_DP_BETA15"."GETALMACENCERT" ;
CREATE PUBLIC SYNONYM GETCLIENTDTOANDGROUP FOR "CLOUD_DP_BETA15"."GETCLIENTDTOANDGROUP" ;
CREATE PUBLIC SYNONYM GETCONNUSER FOR "CLOUD_DP_BETA15"."GETCONNUSER" ;
CREATE PUBLIC SYNONYM GETDEFAULTDTOANDGROUP FOR "CLOUD_DP_BETA15"."GETDEFAULTDTOANDGROUP" ;
CREATE PUBLIC SYNONYM GETSESION FOR "CLOUD_DP_BETA15"."GETSESION" ;
CREATE PUBLIC SYNONYM PGETMIMETYPEBYIDDOC FOR "CLOUD_DP_BETA15"."PGETMIMETYPEBYIDDOC" ;
CREATE PUBLIC SYNONYM NOMBRESERVICIOFINDBYID FOR "CLOUD_DP_BETA15"."NOMBRESERVICIOFINDBYID" ;
CREATE PUBLIC SYNONYM FORMAJURIDICABYNIF FOR "CLOUD_DP_BETA15"."FORMAJURIDICABYNIF" ;
CREATE PUBLIC SYNONYM GETBUCKET FOR "CLOUD_DP_BETA15"."GETBUCKET" ;
CREATE PUBLIC SYNONYM GETURLNUBE FOR "CLOUD_DP_BETA15"."GETURLNUBE"; 
CREATE PUBLIC SYNONYM GET_DOCCONSULTA FOR "CLOUD_DP_BETA15"."GET_DOCCONSULTA"; 


--PAQUETES
CREATE PUBLIC SYNONYM PKCONSULTASFISCAL FOR "CLOUD_DP_BETA15"."PKCONSULTASFISCAL" ;
CREATE PUBLIC SYNONYM PKCRIPTOCLOUDDP FOR "CLOUD_DP_BETA15"."PKCRIPTOCLOUDDP" ;
CREATE PUBLIC SYNONYM PKDOCSYSTEMCUSTODY FOR "CLOUD_DP_BETA15"."PKDOCSYSTEMCUSTODY" ;
CREATE PUBLIC SYNONYM PKEDITUSUARIOS FOR "CLOUD_DP_BETA15"."PKEDITUSUARIOS" ;
CREATE PUBLIC SYNONYM PKMENSAJES FOR "CLOUD_DP_BETA15"."PKMENSAJES" ;
CREATE PUBLIC SYNONYM PKSESIONES FOR "CLOUD_DP_BETA15"."PKSESIONES" ;
CREATE PUBLIC SYNONYM PKUSERSCDP FOR "CLOUD_DP_BETA15"."PKUSERSCDP" ;
CREATE PUBLIC SYNONYM PKWORKFORCE FOR "CLOUD_DP_BETA15"."PKWORKFORCE"; 
CREATE PUBLIC SYNONYM PKTABLON FOR "CLOUD_DP_BETA15"."PKTABLON" ;
CREATE PUBLIC SYNONYM PKCARPETAS FOR "CLOUD_DP_BETA15"."PKCARPETAS" ;

--VISTAS
CREATE PUBLIC SYNONYM VW_DOCSINVITADO FOR "CLOUD_DP_BETA15"."VW_DOCSINVITADO" ;
CREATE PUBLIC SYNONYM VW_DOCSCLIENTE FOR "CLOUD_DP_BETA15"."VW_DOCSCLIENTE" ;
CREATE PUBLIC SYNONYM VW_EMPLEADOS FOR "CLOUD_DP_BETA15"."VW_EMPLEADOS" ;
CREATE PUBLIC SYNONYM VW_INVITADOS FOR "CLOUD_DP_BETA15"."VW_INVITADOS" ;
CREATE PUBLIC SYNONYM VW_INVITADOSACTIVOS FOR "CLOUD_DP_BETA15"."VW_INVITADOSACTIVOS" ;
CREATE PUBLIC SYNONYM VW_INVITADOSBAJA FOR "CLOUD_DP_BETA15"."VW_INVITADOSBAJA" ;
CREATE PUBLIC SYNONYM VW_BUZONENTRADA FOR "CLOUD_DP_BETA15"."VW_BUZONENTRADA" ;
CREATE PUBLIC SYNONYM VW_BUZONSALIDA FOR "CLOUD_DP_BETA15"."VW_BUZONSALIDA" ;
CREATE PUBLIC SYNONYM VW_ASUNTOSPENDIENTES FOR "CLOUD_DP_BETA15"."VW_ASUNTOSPENDIENTES" ;
CREATE PUBLIC SYNONYM VW_HILOS FOR "CLOUD_DP_BETA15"."VW_HILOS" ;

--TABLAS
CREATE PUBLIC SYNONYM WEB_PERSONAL FOR "CLOUD_DP_BETA15"."WEB_PERSONAL" ;
CREATE PUBLIC SYNONYM TIPOS_DOC FOR "CLOUD_DP_BETA15"."TIPOS_DOC" ;
CREATE PUBLIC SYNONYM TEMPCONSULTAS FOR "CLOUD_DP_BETA15"."TEMPCONSULTAS" ;
CREATE PUBLIC SYNONYM VISTASINTERFAZ FOR "CLOUD_DP_BETA15"."VISTASINTERFAZ"; 
CREATE PUBLIC SYNONYM TABLON FOR "CLOUD_DP_BETA15"."TABLON" ;
CREATE PUBLIC SYNONYM FORMASJURIDICAS FOR "CLOUD_DP_BETA15"."FORMASJURIDICAS" ;
CREATE PUBLIC SYNONYM TMP_CORPUS FOR "CLOUD_DP_BETA15"."TMP_CORPUS" ;
CREATE PUBLIC SYNONYM TEMP_CARPETAS FOR "CLOUD_DP_BETA15"."TEMP_CARPETAS" ;
CREATE PUBLIC SYNONYM CONSULTAS FOR "CLOUD_DP_BETA15"."CONSULTAS" ;
CREATE PUBLIC SYNONYM CARPETASUSUARIO FOR "CLOUD_DP_BETA15"."CARPETASUSUARIO" ;
CREATE PUBLIC SYNONYM TMPBLOB FOR "CLOUD_DP_BETA15"."TMPBLOB" ;